package ahhascsystem;

import javax.swing.JOptionPane;

public class ModifyCustomer extends javax.swing.JFrame {

    /**
     * Creates new form ModifyCustomer
     */
    public ModifyCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getPassword = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        showPassword = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        getConfirmPassword = new javax.swing.JPasswordField();
        showConfirmPasword = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Account");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify Your Account");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        getUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        getPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        showPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showPassword.setText("Show");
        showPassword.setToolTipText("");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");

        getConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        showConfirmPasword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showConfirmPasword.setText("Show");
        showConfirmPasword.setToolTipText("");
        showConfirmPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConfirmPaswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(getPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(getUsername)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(getConfirmPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showConfirmPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showConfirmPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(confirmBtn))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        //cancel button code
//        AHHASCSystem.modifyCustomer.setVisible(false);
//        AHHASCSystem.customerMenu.setVisible(true);
        resetForm();
        CustomerMenu.modifyCustomer.setVisible(false);
        LoginPage.customerMenu.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (getUsername.getText().equals("") || getPassword.getText().equals("") ||  getConfirmPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please ensure that all fields are filled in!");
        } else {
            try {
                String username = getUsername.getText();
                String pass = getPassword.getText();
                int password = Integer.parseInt(pass);
                String cpass = getConfirmPassword.getText();
                int confirmpassword = Integer.parseInt(cpass);
                
                if (pass.startsWith("0") || cpass.startsWith("0")) {
                    JOptionPane.showMessageDialog(null, "Passwords cannot start with zero! (0)");
                } else if (password == confirmpassword) {
                    
                    //If username was edited, it will check if new username already exists.

                    if (!username.equals(AHHASCSystem.customerlogin.getName())) {
                        if (DataIO.checkNameCustomer(username) != null) {
                            throw new Exception(); 
                        }
                    }    
                    
                    AHHASCSystem.customerlogin.setName(username);
                    AHHASCSystem.customerlogin.setPassword(password);
                    DataIO.writeUser();
                    JOptionPane.showMessageDialog(null, "Successfully modified customer.");
//                    AHHASCSystem.modifyCustomer.setVisible(false);
//                    AHHASCSystem.customerMenu.setVisible(true);
                    resetForm();
                    CustomerMenu.modifyCustomer.setVisible(false);
                    LoginPage.customerMenu.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Your passwords did not match.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input!");
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            getPassword.setEchoChar((char)0);
            showPassword.setText("Hide");
        } else {
            getPassword.setEchoChar('•');
            showPassword.setText("Show");
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void showConfirmPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConfirmPaswordActionPerformed
        if (showConfirmPasword.isSelected()) {
            getConfirmPassword.setEchoChar((char)0);
            showConfirmPasword.setText("Hide");
        } else {
            getConfirmPassword.setEchoChar('•');
            showConfirmPasword.setText("Show");
        }
    }//GEN-LAST:event_showConfirmPaswordActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String EditUsername = AHHASCSystem.customerlogin.getName();
        int EditPassword = AHHASCSystem.customerlogin.getPassword();
        getUsername.setText(EditUsername);
        getPassword.setText(String.valueOf(EditPassword));
        getConfirmPassword.setText(String.valueOf(EditPassword));
    }//GEN-LAST:event_formWindowOpened

    public void resetForm() {
        String EditUsername = AHHASCSystem.customerlogin.getName();
        int EditPassword = AHHASCSystem.customerlogin.getPassword();
        getUsername.setText(EditUsername);
        getPassword.setText(String.valueOf(EditPassword));
        getConfirmPassword.setText(String.valueOf(EditPassword));  
        showPassword.setSelected(false);
        getPassword.setEchoChar('•');
        showPassword.setText("Show");
        showConfirmPasword.setSelected(false);
        getConfirmPassword.setEchoChar('•');
        showConfirmPasword.setText("Show");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPasswordField getConfirmPassword;
    private javax.swing.JPasswordField getPassword;
    private javax.swing.JTextField getUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton showConfirmPasword;
    private javax.swing.JToggleButton showPassword;
    // End of variables declaration//GEN-END:variables
}
