package ahhascsystem;

import javax.swing.JOptionPane;

public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        getConfirmPassword = new javax.swing.JPasswordField();
        confirmBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        selectUserType = new javax.swing.JComboBox<>();
        showPassword = new javax.swing.JToggleButton();
        showConfirmPassword = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Register Account");

        getUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("User Type");

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");

        selectUserType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Technician", "Manager", "Customer" }));

        showPassword.setText("Show");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        showConfirmPassword.setText("Show");
        showConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConfirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(selectUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(getConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(getPassword, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(showPassword))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(showConfirmPassword)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(confirmBtn))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        ManagerMenu.registerPage.setVisible(false);
        LoginPage.managerMenu.setVisible(true);
        clearForm();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (getUsername.getText().equals("") || getPassword.getText().equals("") ||  getConfirmPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please ensure that all fields are filled in!");
        } else {
            try {
                String username = getUsername.getText();
                String pass = getPassword.getText();
                int password = Integer.parseInt(pass);
                String cpass = getConfirmPassword.getText();
                int confirmpassword = Integer.parseInt(cpass);
                String role = selectUserType.getSelectedItem().toString();
                
                if (pass.startsWith("0") || cpass.startsWith("0")) {
                    JOptionPane.showMessageDialog(null, "Passwords cannot start with zero! (0)");
                    //passwords cannot start with 0 because the 0 will be omitted when converted to an integer
                } else {
                    if (password == confirmpassword) {
                        switch (role) {
                            case "Select":
                                JOptionPane.showMessageDialog(null, "Please select a user!");
                                break;
                            case "Technician":
                                Technician TechFound = DataIO.checkNameTech(username);
                                if (TechFound != null) {
                                    throw new Exception(); 
                                }
                                DataIO.allTechnicians.add(new Technician(username,password));
                                DataIO.writeUser();
                                JOptionPane.showMessageDialog(null, "Successfully registered new technician.");
                                clearForm();
                                break;

                            case "Manager":
                                Manager ManagerFound = DataIO.checkNameManager(username);
                                if (ManagerFound != null) {
                                    throw new Exception(); 
                                }
                                DataIO.allManagers.add(new Manager(username,password));
                                DataIO.writeUser();
                                JOptionPane.showMessageDialog(null, "Successfully registered new manager.");
                                clearForm();
                                break;
                                
                            case "Customer":
                                Customer CustomerFound = DataIO.checkNameCustomer(username);
                                if (CustomerFound != null) {
                                    throw new Exception(); 
                                }
                                DataIO.allCustomers.add(new Customer(username,password));
                                DataIO.writeUser();
                                JOptionPane.showMessageDialog(null, "Successfully registered new customer.");
                                clearForm();                                 
                        }    
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Your passwords did not match.");
                    }
                }     
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input!");
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            getPassword.setEchoChar((char)0);
            showPassword.setText("Hide");
        } else {
            getPassword.setEchoChar('•');
            showPassword.setText("Show");
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void showConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConfirmPasswordActionPerformed
        if (showConfirmPassword.isSelected()) {
            getConfirmPassword.setEchoChar((char)0);
            showConfirmPassword.setText("Hide");
        } else {
            getConfirmPassword.setEchoChar('•');
            showConfirmPassword.setText("Show");
        }
    }//GEN-LAST:event_showConfirmPasswordActionPerformed

    public void clearForm() {
        getUsername.setText("");
        getPassword.setText("");
        getConfirmPassword.setText("");
        selectUserType.setSelectedItem("Select");
        showPassword.setSelected(false);
        getPassword.setEchoChar('•');
        showPassword.setText("Show");
        showConfirmPassword.setSelected(false);
        getPassword.setEchoChar('•');
        showConfirmPassword.setText("Show");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPasswordField getConfirmPassword;
    private javax.swing.JPasswordField getPassword;
    private javax.swing.JTextField getUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectUserType;
    private javax.swing.JToggleButton showConfirmPassword;
    private javax.swing.JToggleButton showPassword;
    // End of variables declaration//GEN-END:variables
}
